name=str(input("Name: "))
phn_num=int(input("Phone Number: "))
course=input("Course Enrolled: ")
print(name," is a", type(name))
print(phn_num,"is a",type(phn_num))
print(course,"is a",type(course))